version: "2"
services:
  redis:
    image: bitnami/redis:6.2
    restart: always
    volumes:
      - ./data:/bitnami/redis/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
